### PR TITLE
Avoid app crash when setting invalid sample rate when playing DSD file.

### LINKED ISSUE #56: Prevent dsd player crash
Currently, only DSD64 is supported, prevent app crash if the selected file is not a DSD64.

### PR DESCRIPTION
**Pull request by flamme**
Fixes #56

### CODE REVIEW

File: app/src/main/java/com/google/android/soundchecker/dsd/DsfReader.kt [hunk 1]
```diff
@@ -271,7 +271,12 @@ class DsfReader(inputStream: InputStream) {
             Log.e(TAG, "Unable to read sample rate")
             return false
         }
-        mAudioFormatBuilder.setSampleRate(sampleRate.toInt() / 16)
+        try {
+            mAudioFormatBuilder.setSampleRate(sampleRate.toInt() / 16)
+        } catch (e : Exception) {
+            Log.e(TAG, "Failed to set sample rate: ${sampleRate.toInt()}")
```
Comment (robertwu1) [inline app/src/main/java/com/google/android/soundchecker/dsd/DsfReader.kt:277]: can we fire a toast instead so the user can see it in the ui?

**Review by robertwu1 — APPROVED** [review]
